name: Deploy Infra + Configure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform Action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Environment
        env:
          TF_IN_AUTOMATION: true
          TF_INPUT: false
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
        run: echo "Terraform environment variables set"
     
      # - name: Generate terraform variables file
      #   working-directory: terraform
      #   run: |
      #     cat <<EOF > terraform.tfvars
      #     db_password = "${{ secrets.DB_PASSWORD }}"
      #     key_name    = "${{ secrets.KEY_NAME }}"
      #     EOF

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.environment == 'plan'
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.event.inputs.environment == 'apply'
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.environment == 'destroy'
        working-directory: terraform
        run: terraform destroy -auto-approve
        
      - name: Capture Terraform Outputs
        if: github.event.inputs.environment == 'apply'
        working-directory: terraform
        run: |
         echo "BASTION_IP=$(terraform output -raw bastion_ip)" >> $GITHUB_ENV
         echo "APP_IP=$(terraform output -raw app_private_ip)" >> $GITHUB_ENV
          
      - name: Show Outputs
        if: github.event.inputs.environment == 'apply'
        run: |
             echo "BASTION Node IP: ${{ env.BASTION_IP }}"

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip

      - name: Wait for SSH
        run: sleep 60

      - name: Create Ansible Inventory
        if: github.event.inputs.environment == 'apply'
        run: |
          cat <<EOF > inventory.ini
          [bastion]
          ${{ env.BASTION_IP }}

          [app]
          ${{ env.APP_IP }}

          [app:vars]
          ansible_user=ec2-user
          ansible_ssh_private_key_file=~/.ssh/${{ secrets.KEY_NAME }}.pem
          ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/${{ secrets.KEY_NAME }}.pem ec2-user@${{ env.BASTION_IP }}"'
          EOF

      - name: Show Inventory
        if: github.event.inputs.environment == 'apply'
        run: cat terraform/inventory.ini

      - name: Create SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.aws_ssh_key }}" > ~/.ssh/${{ secrets.KEY_NAME }}.pem
          chmod 400 ~/.ssh/${{ secrets.KEY_NAME }}.pem

      - name: test ssh connection
        if: github.event.inputs.environment == 'apply'
        run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.KEY_NAME }}.pem ec2-user@${{ env.BASTION_IP }} "echo SSH OK"
          chmod 400 ~/.ssh/${{ secrets.KEY_NAME }}.pem

      - name: Run Ansible
        if: github.event.inputs.environment == 'apply'
        run: |
          ansible-playbook -i terraform/inventory.ini ansible/playbook.yml
